files.extend-exclude = [
	"machines/*/secrets.yaml",
	"homes/*/secrets.yaml",
]

default.extend-ignore-re = [
	'''(?m)^.*# typos:ignore-line$'''
]

[default.extend-identifiers]
mosquitto = "mosquitto"
LESS_TERMCAP_ue = "LESS_TERMCAP_ue"
