#!/bin/bash

DIR="$HOME/.xmonad"

if [ -f ~/.desktop_type ]; then
	CONFIG=$(cat ~/.desktop_type)
elif [ -f /proc/acpi/battery/BAT0/ ]; then
	CONFIG=laptop
else
	CONFIG=desktop
fi

if [ "$CONFIG" = work ]; then
	cpp -P -I"$DIR" -DCONFIG_WORK ~/.xmonad/xmonad.hs.in >~/.xmonad/xmonad.hs
else
	cpp -P -I"$DIR" -DCONFIG_DESKTOP ~/.xmonad/xmonad.hs.in >~/.xmonad/xmonad.hs
fi

if [ "$CONFIG" = work ]; then
	xrandr --output HDMI-1 --rotate left --left-of DP-3
	xrandr --output DP-1 --rotate left --right-of DP-3
fi

if [ -f ~/.wallpaper.png ]; then
	xwallpaper --zoom ~/.wallpaper.png
fi

cpp -P -I"$DIR" ~/.Xdefaults.edit >~/.Xdefaults

xrdb ~/.Xresources
xsetroot -cursor_name left_ptr -solid '#000000'
setxkbmap pl
xset r rate 250 35
if [ "$CONFIG" = work ]; then
	xautolock -corners '0+00' -locker ~/.slock/slock_wrapper.sh -cornerdelay 2 -cornerredelay 10 -time 3 &
else
	echo
fi
xset s off
xset dpms 120 120 120
xset m 7/4 7

pkill -9 -f panels_wrapper.sh

(wait_for_x_prop __XMONAD_STARTUP_DONE__ 1 && (
	picom &
)) &

# TODO: temporary envs (should eventually be managed by nix)
export XMONAD_FONT="$(cpp -P -I"$DIR" - <<<'#include "xmonad.rc"'$'\n''XMONAD_FONT')"
export HEIGHT="$(cpp -P -I"$DIR" - <<<'#include "xmonad.rc"'$'\n''HEIGHT')"
export HEIGHT_TABS="$(cpp -P -I"$DIR" - <<<'#include "xmonad.rc"'$'\n''HEIGHT_TABS')"

ulimit -s 16000 && xmonad

# clean up xmonad's mess
pkill -9 -f panels_wrapper.sh
