name: Flake Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run flake check
        run: nix flake check --all-systems
